#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.


STORED_ASSETS="${OPENSHIFT_DATA_DIR}/assets"
LIVE_ASSETS="${OPENSHIFT_REPO_DIR}/public/assets"

# Ensure our stored assets directory exists
if [ ! -d "${STORED_ASSETS}" ]; then
  echo "  Creating permanent assets directory"
  mkdir "${STORED_ASSETS}"
fi

# Create symlink to stored assets unless we're uploading our own assets
#if [ -d "${LIVE_ASSETS}" ]; then
# echo "  WARNING: Assets included in git repository, not using stored assets"
#else
  echo "  Restoring stored assets"
  ln -sf "${STORED_ASSETS}" "${LIVE_ASSETS}"
#fi

# Run db:migrate
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake db:migrate RAILS_ENV="production"
popd > /dev/null

# Run db:seed
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake db:seed RAILS_ENV="production"
popd > /dev/null
